name: Run utils.py every morning at 6:00 AM PST

on:
  schedule:
    - cron: "0 13 * * *"

jobs:
  run-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x # Replace with your desired Python version
      - name: Install dependencies
        run: pip install -r requirements.txt # Replace with your dependencies file name
      - name: Run utils.py
        run: python utils.py
