name: Run utils.py and push changes to the repository every morning at 6:00 AM PST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run utils.py
        run: python utils.py
      - name: Commit and push changes to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update bets"
          commit_options: "--no-verify"
          file_pattern: "todays_bets.csv"
          branch: master

